print("1. Este Pokémon es una serpiente venenosa con un patrón de colores brillantes en su cuerpo. Puede aprender movimientos de tipo veneno y tipo planta")
print("2. Es un Pokémon con una concha dura y puede disparar agua a alta presión desde sus cañones de agua en su espalda. Es de tipo agua")
print("3. Este Pokémon es un pájaro grande de tipo volador. Es conocido por su velocidad y su capacidad para crear ráfagas de viento con sus alas.")
print("4. Es un Pokémon dragón que puede lanzar llamas ardientes de su boca. Es el último eslabón de una evolución de tres etapas.")
print("5. Este Pokémon es un pequeño roedor eléctrico con mejillas rojas y amarillas. Es la mascota más icónica de la franquicia Pokémon.")
print("Soluciones: ")
print("1. La serpiente venenosa con un patrón de colores brillantes es Ekans.")
print("2. El Pokémon con una concha dura y cañones de agua en su espalda es Squirtle.")
print("3. El pájaro grande de tipo volador es Pidgeot.")
print("4. El dragón que lanza llamas ardientes de su boca es Charizard.")
print("5. El pequeño roedor eléctrico con mejillas rojas y amarillas es Pikachu.")
